apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: blog
build:
  artifacts:
  - image: clstb/blog
    docker:
      dockerfile: Dockerfile
deploy:
  kubeContext: mosquito
  kustomize:
    paths:
    - k8s/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod
